spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

nbp:
  client:
    connection-properties:
      base-url: ${NBP_BASE_URL:https://api.nbp.pl}
  scheduler:
    upsert-exchange-rates-cron: ${UPSERT_EXCHANGE_RATES_CRON:0/15 * * * * *}