spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    username: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: postgres

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

nbp:
  client:
    connection-properties:
      base-url: https://api.nbp.pl
  scheduler:
    update-exchange-rates-on-startup: true
    update-exchange-rates-cron: 0/15 * * * * *